name: verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup-go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: 'stable'

      - name: setup-osquery
        run: |
         curl -LO https://pkg.osquery.io/deb/osquery_5.11.0-1.linux_amd64.deb
         sudo dpkg -i osquery_5.11.0-1.linux_amd64.deb

      - name: verify
        run: make verify-ci

